[package]
name = "mysqlbinlog-network"
version = "0.1.0"
authors = ["jiuker <guozhi.li@dmall.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql_binlog = "0.3.1"
byteorder = "*"
sha1 = "0.6.0"
hmac-sha256 = "0.1.6"
sys-info="*"